INSERT INTO plantas_cultivo (id, nome, especie, categoria, sol_necessario, frequencia_rega, tipo_vaso) VALUES 
(1, 'Jiboia', 'Epipremnum aureum', 'Folhagem', 'Luz indireta (2-4h)', '2x por semana', 'Médio (Pendurado)'),
(2, 'Espada-de-São-Jorge', 'Dracaena trifasciata', 'Folhagem', 'Direto ou indireto (2-6h)', '1x a cada 15 dias', 'Barro ou Cerâmica'),
(3, 'Zamioculca', 'Zamioculcas zamiifolia', 'Folhagem', 'Luz indireta (1-2h)', '1x por semana', 'Plástico ou Cerâmica'),
(4, 'Maranta-Pena-de-Pavão', 'Maranta leuconeura', 'Folhagem', 'Luz indireta (Sombra)', '3x por semana', 'Plástico'),
(5, 'Singônio', 'Syngonium podophyllum', 'Folhagem', 'Luz indireta (2-4h)', '2x por semana', 'Plástico ou Barro'),
(6, 'Filodendro-Brasil', 'Philodendron hederaceum', 'Folhagem', 'Luz indireta (3-4h)', '2x por semana', 'Médio (Pendurado)'),
(7, 'Clorofito', 'Chlorophytum comosum', 'Folhagem', 'Luz indireta/Direta (3h)', '2x por semana', 'Pequeno/Médio'),
(8, 'Peperômia-Melancia', 'Peperomia argyreia', 'Folhagem', 'Luz indireta (2-3h)', '1x a 2x por semana', 'Pequeno'),
(9, 'Dinheiro-em-penca', 'Callisia repens', 'Folhagem', 'Luz indireta (3-4h)', '3x por semana', 'Cuia (Pendurado)'),
(10, 'Lambari-roxo', 'Tradescantia zebrina', 'Folhagem', 'Sol direto/Indireto (4h)', '2x por semana', 'Cuia (Pendurado)'),
(11, 'Costela-de-Adão', 'Monstera deliciosa', 'Folhagem', 'Luz indireta (3-5h)', '1x a 2x por semana', 'Grande e fundo'),
(12, 'Palmeira-Ráfia', 'Rhapis excelsa', 'Folhagem', 'Luz indireta (2-4h)', '1x por semana', 'Grande (Coluna)'),
(13, 'Palmeira-Areca', 'Dypsis lutescens', 'Folhagem', 'Sol direto/Indireto (4h+)', '2x por semana', 'Grande'),
(14, 'Pau-d’água', 'Dracaena fragrans', 'Folhagem', 'Luz indireta (2-3h)', '2x por semana', 'Médio/Grande'),
(15, 'Samambaia-Americana', 'Nephrolepis exaltata', 'Folhagem', 'Luz indireta (Sombra clara)', 'Diária ou 3x/semana', 'Cuia de Fibra/Plástico'),
(16, 'Avenca', 'Adiantum capillus-veneris', 'Folhagem', 'Luz indireta (Sombra)', 'Diária', 'Plástico'),
(17, 'Chifre-de-veado', 'Platycerium bifurcatum', 'Folhagem', 'Luz indireta (2-4h)', '2x por semana', 'Madeira ou Plástico'),
(18, 'Hera-inglesa', 'Hedera helix', 'Folhagem', 'Sol direto/Indireto (4h)', '2x por semana', 'Médio (Pendurado)'),
(19, 'Fícus-Lirata', 'Ficus lyrata', 'Folhagem', 'Luz indireta (4-6h)', '1x por semana', 'Grande e pesado'),
(20, 'Ficus-Elastica', 'Ficus elastica', 'Folhagem', 'Sol direto/Indireto (4h)', '1x por semana', 'Grande'),
(21, 'Aspargo-alfinete', 'Asparagus densiflorus', 'Folhagem', 'Luz indireta (3-4h)', '2x por semana', 'Médio (Pendurado)'),
(22, 'Croton', 'Codiaeum variegatum', 'Folhagem', 'Sol direto (6h+)', '2x a 3x por semana', 'Barro ou Cerâmica'),
(23, 'Aglaonema', 'Aglaonema commutatum', 'Folhagem', 'Luz indireta (1-2h)', '2x por semana', 'Médio'),
(24, 'Calathea-Ornata', 'Calathea ornata', 'Folhagem', 'Luz indireta (Sombra)', '3x por semana', 'Plástico'),
(25, 'Comigo-ninguém-pode', 'Dieffenbachia seguine', 'Folhagem', 'Luz indireta (2-3h)', '2x por semana', 'Médio'),
(26, 'Pacová', 'Philodendron martianum', 'Folhagem', 'Luz indireta (2-3h)', '1x por semana', 'Médio/Grande'),
(27, 'Fitônia', 'Fittonia albivenis', 'Folhagem', 'Luz indireta (Sombra)', 'Diária', 'Pequeno'),
(28, 'Bambu-da-sorte', 'Dracaena sanderiana', 'Folhagem', 'Luz indireta (1-2h)', 'Troca de água', 'Vidro ou Vaso pequeno'),
(29, 'Columeia-batom', 'Aeschynanthus radicans', 'Folhagem', 'Luz indireta (3-4h)', '2x por semana', 'Cuia (Pendurado)'),
(30, 'Peperômia-scandens', 'Peperomia nitida', 'Folhagem', 'Luz indireta (2-4h)', '2x por semana', 'Médio (Pendurado)'),
(31, 'Pilea', 'Pilea peperomioides', 'Folhagem', 'Luz indireta (3-4h)', '1x a 2x por semana', 'Pequeno/Médio'),
(32, 'Begônia-rex', 'Begonia rex-cultorum', 'Folhagem', 'Luz indireta (2-3h)', '2x por semana', 'Barro ou Plástico'),
(33, 'Ripsális', 'Rhipsalis baccifera', 'Folhagem', 'Luz indireta (3-4h)', '1x por semana', 'Médio (Pendurado)'),
(34, 'Planta-mosaico', 'Ludisia discolor', 'Folhagem', 'Luz indireta (Sombra)', '2x por semana', 'Pequeno'),
(35, 'Alocásia-Polly', 'Alocasia amazonica', 'Folhagem', 'Luz indireta (3-4h)', '2x por semana', 'Médio'),
(36, 'Violeta-africana', 'Saintpaulia ionantha', 'Flor', 'Luz indireta (4h)', '2x por semana', 'Pequeno (Barro)'),
(37, 'Orquídea', 'Phalaenopsis x hybridus', 'Flor', 'Luz indireta (3-4h)', '1x por semana', 'Transparente'),
(38, 'Antúrio', 'Anthurium andraeanum', 'Flor', 'Luz indireta (4h)', '2x a 3x por semana', 'Médio'),
(39, 'Lírio-da-paz', 'Spathiphyllum wallisii', 'Flor', 'Luz indireta (2-4h)', '3x por semana', 'Médio'),
(40, 'Gerânio', 'Pelargonium hortorum', 'Flor', 'Sol direto (6h+)', '2x por semana', 'Barro'),
(41, 'Kalanchoe', 'Kalanchoe blossfeldiana', 'Flor', 'Sol direto (4-6h)', '1x por semana', 'Pequeno (Barro)'),
(42, 'Begônia', 'Begonia semperflorens', 'Flor', 'Luz indireta/Direta (4h)', '2x por semana', 'Pequeno/Médio'),
(43, 'Onze-horas', 'Portulaca grandiflora', 'Flor', 'Sol direto (6h+)', '1x a 2x por semana', 'Cuia rasa'),
(44, 'Mini-rosa', 'Rosa chinensis', 'Flor', 'Sol direto (6h+)', 'Diária', 'Barro'),
(45, 'Flor-de-maio', 'Schlumbergera truncata', 'Flor', 'Luz indireta (4h)', '1x a 2x por semana', 'Médio (Pendurado)'),
(46, 'Azaleia', 'Rhododendron simsii', 'Flor', 'Sol direto (4-6h)', 'Diária', 'Barro'),
(47, 'Ciclamen', 'Cyclamen persicum', 'Flor', 'Luz indireta (3h)', '2x por semana', 'Pequeno'),
(48, 'Gérbera', 'Gerbera jamesonii', 'Flor', 'Sol direto (6h)', '2x por semana', 'Médio'),
(49, 'Maria-sem-vergonha', 'Impatiens walleriana', 'Flor', 'Sol indireto', 'Diária', 'Médio'),
(50, 'Flor-de-cera', 'Hoya carnosa', 'Flor', 'Luz indireta (4h)', '1x por semana', 'Médio (Treliça)'),
(51, 'Lavanda', 'Lavandula angustifolia', 'Flor', 'Sol direto (6h+)', '1x a 2x por semana', 'Barro'),
(52, 'Vinca', 'Catharanthus roseus', 'Flor', 'Sol direto (6h+)', '2x por semana', 'Pequeno/Médio'),
(53, 'Amor-perfeito', 'Viola tricolor', 'Flor', 'Sol direto (4-6h)', '3x por semana', 'Pequeno'),
(54, 'Crisântemo', 'Chrysanthemum morifolium', 'Flor', 'Sol direto (4h)', '2x a 3x por semana', 'Médio'),
(55, 'Gardênia', 'Gardenia jasminoides', 'Flor', 'Sol direto/Meia sombra', '3x por semana', 'Médio/Grande'),
(56, 'Primavera (Bonsai)', 'Bougainvillea glabra', 'Flor', 'Sol direto (6h+)', '2x por semana', 'Vaso de Bonsai'),
(57, 'Hibisco', 'Hibiscus rosa-sinensis', 'Flor', 'Sol direto (6h+)', '3x por semana', 'Grande'),
(58, 'Petúnia', 'Petunia x hybrida', 'Flor', 'Sol direto (6h+)', 'Diária', 'Cuia ou Floreira'),
(59, 'Beldroega', 'Portulaca oleracea', 'Flor', 'Sol direto (6h+)', '1x por semana', 'Pequeno/Médio'),
(60, 'Lanterna-chinesa', 'Abutilon striatum', 'Flor', 'Sol direto (4h+)', '2x por semana', 'Médio'),
(61, 'Beijo-pintado', 'Impatiens hawkeri', 'Flor', 'Luz indireta/Direta (4h)', 'Diária', 'Médio'),
(62, 'Gloxínia', 'Sinningia speciosa', 'Flor', 'Luz indireta (4h)', '2x por semana', 'Pequeno'),
(63, 'Calceolária', 'Calceolaria herbeohybrida', 'Flor', 'Luz indireta (3h)', '2x por semana', 'Pequeno'),
(64, 'Flor-de-vidro', 'Impatiens balsamina', 'Flor', 'Luz indireta/Meia sombra', 'Diária', 'Pequeno/Médio'),
(65, 'Estrelítzia', 'Strelitzia reginae', 'Flor', 'Sol direto (6h+)', '2x por semana', 'Grande e fundo'),
(66, 'Manjericão', 'Ocimum basilicum', 'Horta', 'Sol direto (6h+)', 'Diária', 'Médio'),
(67, 'Alecrim', 'Salvia rosmarinus', 'Horta', 'Sol direto (6h+)', '1x a 2x por semana', 'Barro'),
(68, 'Hortelã', 'Mentha spicata', 'Horta', 'Sol direto/Meia sombra', 'Diária', 'Médio (Largo)'),
(69, 'Salsinha', 'Petroselinum crispum', 'Horta', 'Sol direto/Meia sombra', 'Diária', 'Floreira ou Médio'),
(70, 'Cebolinha', 'Allium fistulosum', 'Horta', 'Sol direto (4-6h)', 'Diária', 'Floreira ou Médio'),
(71, 'Tomilho', 'Thymus vulgaris', 'Horta', 'Sol direto (6h+)', '1x por semana', 'Barro pequeno'),
(72, 'Orégano', 'Origanum vulgare', 'Horta', 'Sol direto (6h+)', '2x por semana', 'Médio'),
(73, 'Coentro', 'Coriandrum sativum', 'Horta', 'Sol direto (4-6h)', 'Diária', 'Médio (Profundo)'),
(74, 'Sálvia', 'Salvia officinalis', 'Horta', 'Sol direto (6h+)', '2x por semana', 'Barro médio'),
(75, 'Manjerona', 'Origanum majorana', 'Horta', 'Sol direto (6h)', '2x por semana', 'Pequeno/Médio'),
(76, 'Arruda', 'Ruta graveolens', 'Horta', 'Sol direto (6h+)', '2x por semana', 'Médio'),
(77, 'Pimenta-malagueta', 'Capsicum frutescens', 'Horta', 'Sol direto (6h+)', '3x por semana', 'Médio'),
(78, 'Pimenta-biquinho', 'Capsicum chinense', 'Horta', 'Sol direto (6h+)', '3x por semana', 'Médio'),
(79, 'Tomate-cereja', 'Solanum lycopersicum', 'Horta', 'Sol direto (6h+)', 'Diária', 'Grande'),
(80, 'Morango', 'Fragaria x ananassa', 'Horta', 'Sol direto (6h+)', 'Diária', 'Cuia'),
(81, 'Erva-doce', 'Pimpinella anisum', 'Horta', 'Sol direto (6h)', '2x por semana', 'Médio (Profundo)'),
(82, 'Melissa', 'Melissa officinalis', 'Horta', 'Sol direto/Meia sombra', '3x por semana', 'Médio'),
(83, 'Capim-limão', 'Cymbopogon citratus', 'Horta', 'Sol direto (6h+)', '2x por semana', 'Grande'),
(84, 'Louro', 'Laurus nobilis', 'Horta', 'Sol direto (4-6h)', '1x a 2x por semana', 'Grande'),
(85, 'Boldo', 'Peumus boldus', 'Horta', 'Sol direto (6h+)', '2x por semana', 'Médio'),
(86, 'Poejo', 'Mentha pulegium', 'Horta', 'Sol direto/Meia sombra', 'Diária', 'Pequeno/Médio'),
(87, 'Manjericão-roxo', 'Ocimum basilicum purpurascens', 'Horta', 'Sol direto (6h+)', 'Diária', 'Médio'),
(88, 'Alface-baby', 'Lactuca sativa', 'Horta', 'Sol direto (4h+)', 'Diária', 'Floreira rasa'),
(89, 'Rúcula', 'Eruca sativa', 'Horta', 'Sol direto (4-6h)', 'Diária', 'Floreira rasa'),
(90, 'Espinafre', 'Spinacia oleracea', 'Horta', 'Sol direto (4h+)', 'Diária', 'Médio'),
(91, 'Alho-poró', 'Allium ampeloprasum', 'Horta', 'Sol direto (6h)', '2x por semana', 'Médio (Profundo)'),
(92, 'Gengibre', 'Zingiber officinale', 'Horta', 'Luz indireta (4h)', '2x por semana', 'Largo e profundo'),
(93, 'Açafrão-da-terra', 'Curcuma longa', 'Horta', 'Sol direto/Meia sombra', '3x por semana', 'Largo e profundo'),
(94, 'Camomila', 'Matricaria chamomilla', 'Horta', 'Sol direto (6h)', '2x por semana', 'Pequeno/Médio'),
(95, 'Alface-mimosa', 'Lactuca sativa var. capitata', 'Horta', 'Sol direto (4h)', 'Diária', 'Floreira'),
(96, 'Dill (Endro)', 'Anethum graveolens', 'Horta', 'Sol direto (6h)', '2x por semana', 'Médio (Profundo)'),
(97, 'Estévia', 'Stevia rebaudiana', 'Horta', 'Sol direto (6h)', '2x por semana', 'Médio'),
(98, 'Manjericão-limão', 'Ocimum citriodorum', 'Horta', 'Sol direto (6h+)', 'Diária', 'Médio'),
(99, 'Mostarda', 'Brassica juncea', 'Horta', 'Sol direto (4-6h)', 'Diária', 'Médio'),
(100, 'Erva-doce-cabeça', 'Foeniculum vulgare', 'Horta', 'Sol direto (6h)', '2x por semana', 'Grande');